# Generated by Django 5.2.5 on 2025-08-28 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('comprobante', models.CharField(max_length=200, verbose_name='# Comprobante')),
                ('banco_llegada', models.CharField(max_length=100, verbose_name='Banco Llegada')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.CharField(blank=True, max_length=200, null=True)),
                ('vendedor', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_factura', models.CharField(blank=True, max_length=100, null=True, verbose_name='# de Factura')),
                ('facturador', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Registro Financiero',
                'verbose_name_plural': 'Registros Financieros',
                'unique_together': {('fecha', 'hora', 'comprobante', 'banco_llegada', 'valor')},
            },
        ),
    ]
