# Generated by Django 5.2.5 on 2025-08-29 16:30

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialrecord',
            name='facturador',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='financialrecord',
            name='numero_factura',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='# de Factura'),
        ),
        migrations.AlterField(
            model_name='financialrecord',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Facturado', 'Facturado'), ('Anulado', 'Anulado')], default='Pendiente', max_length=20),
        ),
        migrations.CreateModel(
            name='HistoricalFinancialRecord',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('comprobante', models.CharField(max_length=200, verbose_name='# Comprobante')),
                ('banco_llegada', models.CharField(max_length=100, verbose_name='Banco Llegada')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.CharField(blank=True, max_length=200, null=True)),
                ('vendedor', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Facturado', 'Facturado'), ('Anulado', 'Anulado')], default='Pendiente', max_length=20)),
                ('numero_factura', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='# de Factura')),
                ('facturador', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Registro Financiero',
                'verbose_name_plural': 'historical Registros Financieros',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
