# Generated by Django 5.2.5 on 2025-08-29 19:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_alter_financialrecord_facturador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialrecord',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default='2024-08-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financialrecord',
            name='modificado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='historicalfinancialrecord',
            name='creado',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 8, 1, 0, 0), editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalfinancialrecord',
            name='modificado',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 8, 1, 0, 0), editable=False),
            preserve_default=False,
        ),
    ]
