# Generated by Django 5.2.5 on 2025-08-29 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_financialrecord_creado_financialrecord_modificado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='financialrecord',
            name='banco_llegada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='records.bank', verbose_name='Banco Llegada'),
        ),
        migrations.AlterField(
            model_name='historicalfinancialrecord',
            name='banco_llegada',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='records.bank', verbose_name='Banco Llegada'),
        ),
    ]
