# Generated by Django 5.2.5 on 2025-09-03 21:19

from django.db import migrations

def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    # Get content type for FinancialRecord model
    financial_record_content_type = ContentType.objects.get(
        app_label='records',
        model='financialrecord'
    )

    # Get permissions
    add_record_perm = Permission.objects.get(
        codename='add_financialrecord',
        content_type=financial_record_content_type
    )
    change_record_perm = Permission.objects.get(
        codename='change_financialrecord',
        content_type=financial_record_content_type
    )
    view_record_perm = Permission.objects.get(
        codename='view_financialrecord',
        content_type=financial_record_content_type
    )

    # Create Digitador group and assign permissions
    digitador_group, created = Group.objects.get_or_create(name='Digitador')
    digitador_group.permissions.add(add_record_perm, view_record_perm)

    # Create Facturador group and assign permissions
    facturador_group, created = Group.objects.get_or_create(name='Facturador')
    facturador_group.permissions.add(change_record_perm, view_record_perm)

class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_rename_authorizeduser_model'),
    ]

    operations = [
        migrations.RunPython(create_groups),
    ]