# Generated by Django 5.2.5 on 2025-09-02 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_populate_default_banks'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='financialrecord',
            unique_together=set(),
        ),
    ]
