# Generated by Django 5.2.5 on 2025-09-03 17:45

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DuplicateRecordAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_attempts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('comprobante', models.CharField(max_length=200, verbose_name='# Comprobante')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.CharField(blank=True, max_length=200, null=True)),
                ('vendedor', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Facturado', 'Facturado'), ('Anulado', 'Anulado')], default='Pendiente', max_length=20)),
                ('numero_factura', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='# de Factura')),
                ('facturador', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('banco_llegada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='records.bank', verbose_name='Banco Llegada')),
            ],
            options={
                'verbose_name': 'Registro Financiero',
                'verbose_name_plural': 'Registros Financieros',
            },
        ),
        migrations.CreateModel(
            name='HistoricalFinancialRecord',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('comprobante', models.CharField(max_length=200, verbose_name='# Comprobante')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.CharField(blank=True, max_length=200, null=True)),
                ('vendedor', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Facturado', 'Facturado'), ('Anulado', 'Anulado')], default='Pendiente', max_length=20)),
                ('numero_factura', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='# de Factura')),
                ('facturador', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('creado', models.DateTimeField(blank=True, editable=False)),
                ('modificado', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('banco_llegada', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='records.bank', verbose_name='Banco Llegada')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Registro Financiero',
                'verbose_name_plural': 'historical Registros Financieros',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
