# Generated by Django 5.2.5 on 2025-09-03 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_accessrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='authorized_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
