# Generated by Django 5.2.5 on 2025-09-03 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_authorized_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='authorized_user',
            new_name='AuthorizedUser',
        ),
    ]
