# Generated by Django 5.2.5 on 2025-09-03 21:19

from django.db import migrations
from django.contrib.auth.management import create_permissions

def create_groups(apps, schema_editor):
    # Manually create permissions before trying to use them
    app_config = apps.get_app_config('records')
    app_config.models_module = True
    create_permissions(app_config, verbosity=0)
    app_config.models_module = None

    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    FinancialRecord = apps.get_model('records', 'FinancialRecord')

    db_alias = schema_editor.connection.alias

    ct_manager = ContentType.objects.db_manager(db_alias)
    financial_record_content_type = ct_manager.get_for_model(FinancialRecord)

    # Get permissions
    add_record_perm = Permission.objects.using(db_alias).get(
        codename='add_financialrecord',
        content_type=financial_record_content_type
    )
    change_record_perm = Permission.objects.using(db_alias).get(
        codename='change_financialrecord',
        content_type=financial_record_content_type
    )
    view_record_perm = Permission.objects.using(db_alias).get(
        codename='view_financialrecord',
        content_type=financial_record_content_type
    )

    # Create Digitador group and assign permissions
    digitador_group, created = Group.objects.using(db_alias).get_or_create(name='Digitador')
    if created:
        digitador_group.permissions.add(add_record_perm, view_record_perm)

    # Create Facturador group and assign permissions
    facturador_group, created = Group.objects.using(db_alias).get_or_create(name='Facturador')
    if created:
        facturador_group.permissions.add(change_record_perm, view_record_perm)

class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_rename_authorizeduser_model'),
    ]

    operations = [
        migrations.RunPython(create_groups),
    ]