# Generated by Django 5.2.5 on 2025-09-14 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_alter_authorizeduser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='duplicaterecordattempt',
            name='attempt_type',
            field=models.CharField(choices=[('DUPLICATE', 'Duplicado Exacto'), ('SIMILAR', 'Posible Duplicado (Confirmado)')], default='DUPLICATE', max_length=20),
        ),
    ]
