# Generated by Django 5.2.5 on 2025-09-29 16:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_duplicaterecordattempt_attempt_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción de la Transacción')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Transacción')),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
            },
        ),
        migrations.AddField(
            model_name='financialrecord',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='records.transaction', verbose_name='Transacción'),
        ),
        migrations.AddField(
            model_name='historicalfinancialrecord',
            name='transaction',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='records.transaction', verbose_name='Transacción'),
        ),
    ]
