# Generated by Django 5.2.5 on 2025-09-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_transaction_financialrecord_transaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción de la Transacción'),
        ),
    ]
