# Generated by Django 5.2.5 on 2025-09-30 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0010_transaction_cliente_transaction_vendor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='vendor',
            new_name='vendedor',
        ),
    ]
