# Generated by Django 5.2.5 on 2025-10-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0011_rename_vendor_transaction_vendedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialrecord',
            name='facturador',
        ),
        migrations.RemoveField(
            model_name='financialrecord',
            name='numero_factura',
        ),
        migrations.RemoveField(
            model_name='financialrecord',
            name='status',
        ),
        migrations.RemoveField(
            model_name='historicalfinancialrecord',
            name='facturador',
        ),
        migrations.RemoveField(
            model_name='historicalfinancialrecord',
            name='numero_factura',
        ),
        migrations.RemoveField(
            model_name='historicalfinancialrecord',
            name='status',
        ),
        migrations.AddField(
            model_name='transaction',
            name='facturador',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='numero_factura',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='# de Factura'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Facturado', 'Facturado'), ('Anulado', 'Anulado')], default='Pendiente', max_length=20, verbose_name='Estado de Transacción'),
        ),
    ]
