# Generated by Django 5.2.5 on 2025-10-17 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0013_historicaltransaction'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='financialrecord',
            unique_together={('fecha', 'hora', 'comprobante', 'banco_llegada', 'valor')},
        ),
    ]
