# Generated by Django 5.2.5 on 2025-10-22 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0014_alter_financialrecord_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Vendedor',
                'verbose_name_plural': 'Vendedores',
            },
        ),
    ]
