# Generated by Django 5.2.5 on 2025-10-22 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0015_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialrecord',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='records.seller', verbose_name='Vendedor'),
        ),
        migrations.AlterField(
            model_name='historicalfinancialrecord',
            name='vendedor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='records.seller', verbose_name='Vendedor'),
        ),
        migrations.AlterField(
            model_name='historicaltransaction',
            name='vendedor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='records.seller', verbose_name='Vendedor'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='records.seller', verbose_name='Vendedor'),
        ),
    ]
