# Generated by Django 5.2.5 on 2025-10-23 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0016_alter_financialrecord_vendedor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialrecord',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='financialrecord',
            name='vendedor',
        ),
        migrations.RemoveField(
            model_name='historicalfinancialrecord',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='historicalfinancialrecord',
            name='vendedor',
        ),
    ]
