# Generated by Django 5.2.5 on 2025-10-27 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0017_remove_financialrecord_cliente_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltransaction',
            name='creat_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AddField(
            model_name='historicaltransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='historicaltransaction',
            name='unique_transaction_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='ID unico'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='creat_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='unique_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ID unico'),
        ),
    ]
