# Generated by Django 5.2.5 on 2025-10-27 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0018_historicaltransaction_creat_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrigenTransaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('dias_efectivo', models.IntegerField(default=0, verbose_name='Días para ser efectivo')),
            ],
            options={
                'verbose_name': 'Origen de Transacción',
                'verbose_name_plural': 'Origenes de Transacción',
            },
        ),
        migrations.AddField(
            model_name='financialrecord',
            name='origen_transaccion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='records.origentransaccion', verbose_name='Origen de Transacción'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalfinancialrecord',
            name='origen_transaccion',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='records.origentransaccion', verbose_name='Origen de Transacción'),
        ),
    ]
