# Generated by Django 5.2.5 on 2025-10-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0019_origentransaccion_financialrecord_origen_transaccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialrecord',
            name='payment_status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Anulado', 'Anulado')], default='Pendiente', max_length=20, verbose_name='Estado de pago'),
        ),
        migrations.AddField(
            model_name='historicalfinancialrecord',
            name='payment_status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Anulado', 'Anulado')], default='Pendiente', max_length=20, verbose_name='Estado de pago'),
        ),
    ]
