# Generated by Django 5.2.5 on 2025-10-29 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0021_create_validator_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialrecord',
            name='payment_status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=20, verbose_name='Estado de pago'),
        ),
        migrations.AlterField(
            model_name='historicalfinancialrecord',
            name='payment_status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=20, verbose_name='Estado de pago'),
        ),
    ]
