# Generated by Django 5.2.5 on 2025-11-06 15:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0022_alter_financialrecord_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltransaction',
            name='expected_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Valor Venta'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='expected_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Valor Venta'),
        ),
        migrations.AlterField(
            model_name='financialrecord',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='historicalfinancialrecord',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='historicaltransaction',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Venta'),
        ),
        migrations.AlterField(
            model_name='historicaltransaction',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Observación'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Venta'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Observación'),
        ),
    ]
