# Generated by Django 5.2.5 on 2025-11-07 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0023_historicaltransaction_expected_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltransaction',
            name='expected_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Venta'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='expected_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Venta'),
        ),
    ]
