# Generated by Django 5.2.5 on 2025-11-14 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0024_alter_historicaltransaction_expected_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Transacción',
                'verbose_name_plural': 'Tipos de Transacción',
            },
        ),
        migrations.AddField(
            model_name='historicaltransaction',
            name='transaction_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='records.transactiontype', verbose_name='Tipo de Transacción'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='records.transactiontype', verbose_name='Tipo de Transacción'),
            preserve_default=False,
        ),
    ]
