# Generated by Django 5.2.5 on 2025-11-14 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0025_transactiontype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Cliente')),
                ('dni', models.CharField(max_length=50, verbose_name='DNI / Documento')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.AddField(
            model_name='financialrecord',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='records.client', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='historicalfinancialrecord',
            name='cliente',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='records.client', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='historicaltransaction',
            name='cliente',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='records.client', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='records.client', verbose_name='Cliente'),
        ),
    ]
