# Generated by Django 5.2.5 on 2025-11-18 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0026_client_financialrecord_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='dni',
            field=models.CharField(max_length=50, unique=True, verbose_name='DNI / Documento'),
        ),
    ]
