# Generated by Django 5.2.5 on 2025-11-25 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0027_alter_client_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialrecord',
            name='linked_credit_note',
            field=models.OneToOneField(blank=True, help_text='Vincula esta nota de crédito con su contraparte (positiva o negativa).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_credit_note_pair', to='records.financialrecord'),
        ),
        migrations.AddField(
            model_name='historicalfinancialrecord',
            name='linked_credit_note',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Vincula esta nota de crédito con su contraparte (positiva o negativa).', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='records.financialrecord'),
        ),
        migrations.AlterField(
            model_name='client',
            name='dni',
            field=models.CharField(max_length=50, unique=True, verbose_name='Documento'),
        ),
    ]
