# Generated by Django 5.2.5 on 2025-11-25 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0028_financialrecord_linked_credit_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialrecord',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='historicalfinancialrecord',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción'),
        ),
    ]
