# Generated by Django 5.2.5 on 2025-12-15 18:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0029_financialrecord_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialrecord',
            name='note',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Nota'),
        ),
        migrations.AddField(
            model_name='historicalfinancialrecord',
            name='note',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Nota'),
        ),
        migrations.AlterField(
            model_name='financialrecord',
            name='linked_credit_note',
            field=models.OneToOneField(blank=True, help_text='Vincula este saldo a favor con su contraparte (positiva o negativa).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_credit_note_pair', to='records.financialrecord'),
        ),
        migrations.AlterField(
            model_name='historicalfinancialrecord',
            name='linked_credit_note',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Vincula este saldo a favor con su contraparte (positiva o negativa).', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='records.financialrecord'),
        ),
        migrations.AlterField(
            model_name='historicaltransaction',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Pedido'),
        ),
        migrations.AlterField(
            model_name='historicaltransaction',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Facturado', 'Facturado'), ('Anulado', 'Anulado'), ('No Facturable', 'No Facturable')], default='Pendiente', max_length=20, verbose_name='Estado de Transacción'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Pedido'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Facturado', 'Facturado'), ('Anulado', 'Anulado'), ('No Facturable', 'No Facturable')], default='Pendiente', max_length=20, verbose_name='Estado de Transacción'),
        ),
    ]
