# Generated by Django 5.2.5 on 2026-02-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0030_financialrecord_note_historicalfinancialrecord_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialrecord',
            name='payment_document',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Documento de pago'),
        ),
        migrations.AddField(
            model_name='historicalfinancialrecord',
            name='payment_document',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Documento de pago'),
        ),
    ]
