# Generated by Django 5.2.5 on 2026-02-25 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0031_financialrecord_payment_document_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='records.bank', verbose_name='Banco')),
            ],
            options={
                'verbose_name': 'Documento de Pago',
                'verbose_name_plural': 'Documentos de Pago',
            },
        ),
    ]
