# Generated by Django 5.2.5 on 2026-02-25 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0032_paymentdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialrecord',
            name='payment_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_records', to='records.paymentdocument', verbose_name='Documento de Pago'),
        ),
        migrations.AlterField(
            model_name='historicalfinancialrecord',
            name='payment_document',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='records.paymentdocument', verbose_name='Documento de Pago'),
        ),
    ]
