# Generated by Django 5.2.5 on 2026-02-25 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0033_alter_financialrecord_payment_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialrecord',
            name='payment_document',
            field=models.CharField(blank=True, help_text='Número del documento de pago. Debe iniciar con el prefijo del banco (ej: BAN-25154).', max_length=200, null=True, verbose_name='Documento de Pago'),
        ),
        migrations.AlterField(
            model_name='historicalfinancialrecord',
            name='payment_document',
            field=models.CharField(blank=True, help_text='Número del documento de pago. Debe iniciar con el prefijo del banco (ej: BAN-25154).', max_length=200, null=True, verbose_name='Documento de Pago'),
        ),
    ]
